# French translations for PACKAGE package
# Traductions françaises du paquet PACKAGE.
# Copyright (C) 2010 THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# Automatically generated, 2010.
#
msgid ""
msgstr ""
"Project-Id-Version:  vigilo.connector\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2010-04-23 16:00+0200\n"
"PO-Revision-Date: 2011-02-09 15:52+0100\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: fr_FR <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 0.9.4\n"

#: src/vigilo/connector/client.py:64
#, python-format
msgid "Authentication failure: %s"
msgstr "Échec de l'authentification : %s"

#: src/vigilo/connector/client.py:69 src/vigilo/connector/client.py:70
msgid "Server does not support TLS encryption."
msgstr "Le serveur ne supporte pas le chiffrement TLS."

#: src/vigilo/connector/client.py:117
msgid ""
"The \"watched_topics\" option has now been renamed into "
"\"subscriptions\". Please update your configuration file."
msgstr ""

#: src/vigilo/connector/converttoxml.py:54
#: src/vigilo/connector/converttoxml.py:61
#: src/vigilo/connector/converttoxml.py:67
#, python-format
msgid "Unknown/malformed message type: '%s'"
msgstr "Type de message inconnu ou message mal-formé: '%s'"

#: src/vigilo/connector/converttoxml.py:71
#, python-format
msgid "Got malformed message: %s"
msgstr "Réception d'un message mal-formé: %s"

#: src/vigilo/connector/forwarder.py:34
msgid "no connection"
msgstr ""

#: src/vigilo/connector/forwarder.py:38
msgid "no connection to the XMPP server"
msgstr ""

#: src/vigilo/connector/forwarder.py:99
msgid "Connected to the XMPP bus"
msgstr "Connecté au bus XMPP"

#: src/vigilo/connector/forwarder.py:118
#, python-format
msgid "Lost connection to the XMPP bus (reason: %s)"
msgstr ""

#: src/vigilo/connector/forwarder.py:150
#, python-format
msgid "Unable to forward the message (%(reason)s)"
msgstr ""

#: src/vigilo/connector/forwarder.py:156
msgid ". it has been stored for later retransmission"
msgstr ". Il a été sauvé pour une transmission ultérieure"

#: src/vigilo/connector/forwarder.py:193
#, python-format
msgid "Error trying to save a message to the backup database: %s"
msgstr ""

#: src/vigilo/connector/forwarder.py:239
#, python-format
msgid "Batch sent, waiting for %d replies from the bus"
msgstr ""

#: src/vigilo/connector/forwarder.py:395
#, python-format
msgid "No destination node configured for messages of type '%s'. Skipping."
msgstr "Aucun nœud cible configuré pour les messages de type '%s'. Message ignoré."

#: src/vigilo/connector/main.py:39
#, python-format
msgid "Directory not found: '%(dir)s'"
msgstr "Dossier non trouvé : '%(dir)s'"

#: src/vigilo/connector/main.py:44
#, python-format
msgid "Directory not readable: '%(dir)s'"
msgstr "Dossier inaccessible en lecture : '%(dir)s'"

#: src/vigilo/connector/main.py:49
#, python-format
msgid "Directory not writable: '%(dir)s'"
msgstr "Dossier inaccessible en écriture : '%(dir)s'"

#: src/vigilo/connector/main.py:54
#, python-format
msgid "Directory not executable: '%(dir)s'"
msgstr "Dossier inaccessible en exécution : '%(dir)s'"

#: src/vigilo/connector/nodetoqueuefw.py:59
msgid "Incoming message is too big to be stored in the queue, dropping it."
msgstr ""
"Le message entrant est trop volumineux pour être stocké, message \"\n"
"\"ignoré."

#: src/vigilo/connector/nodetoqueuefw.py:64
#, python-format
msgid "The queue is full, dropping incoming XML message! (%s)"
msgstr "La file est pleine, le message XML entrant a été ignoré! (%s)"

#: src/vigilo/connector/nodetosocketfw.py:24
msgid "socket not connected"
msgstr ""

#: src/vigilo/connector/options.py:13
msgid "Choose the service name"
msgstr ""

#: src/vigilo/connector/options.py:14
msgid "Load this settings.ini file"
msgstr ""

#: src/vigilo/connector/options.py:25
msgid "The configuration file does not exist"
msgstr ""

#: src/vigilo/connector/presence.py:76
msgid "Queue size too high! Switching presence to unavailable."
msgstr ""

#: src/vigilo/connector/presence.py:114
#, python-format
msgid ""
"Another instance of %(user)s@%(host)s has priority %(priority)d ! (me: "
"%(me)s, other: %(other)s)"
msgstr ""

#: src/vigilo/connector/queuetonodefw.py:83
msgid "Received request to shutdown"
msgstr "Réception d'une demande d'arrêt"

#: src/vigilo/connector/queuetonodefw.py:88
msgid "Item is None in consumeQueue, this should never happen!"
msgstr "Objet None reçu dans consumeQueue, ça ne devrait jamais arriver !"

#: src/vigilo/connector/queuetonodefw.py:93
msgid "Stopping QueueToNodeForwarder."
msgstr "Arrêt de QueueToNodeForwarder."

#: src/vigilo/connector/status.py:128
#, python-format
msgid "Stats for %(service)s: %(name)s = %(value)s"
msgstr ""

#: src/vigilo/connector/store.py:142 src/vigilo/connector/store.py:211
#, python-format
msgid "Could not fill the output buffer: %s"
msgstr ""

#: src/vigilo/connector/store.py:164
#, python-format
msgid "Could VACUUM the database: %s"
msgstr ""

